// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwguvnvzomfbdzmbpayc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Z3V2bnZ6b21mYmR6bWJwYXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTgzNTcsImV4cCI6MjA3MDkzNDM1N30.d-g69hIeWBDBSGz8EA0V-wEyfM8fdmAx3tfOX1O6dVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});